baseURL = 'http://localhost:1313/'
languageCode = 'ja'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'NOM技術ブログ'
theme = 'ananke'

[params]
  text_color = 'dark-gray'
  background_color_class = 'bg-navy'
  author = 'ki'
  favicon = '/images/profile.png'
  site_logo = '/images/profile.png'

[[params.ananke_socials]]
  name = 'twitter'
  url  = 'https://twitter.com/kwn_tky'
[[params.ananke_socials]]
  name = 'facebook'
  url  = 'https://www.facebook.com/takaya.tsukamoto.1'